services:
  - type: web
    name: dashboard-financeiro
    env: python
    region: oregon
    plan: free
    branch: main
    buildCommand: pip install -r requirements.txt
    startCommand: streamlit run src/main.py --server.port=$PORT --server.address=0.0.0.0 --server.headless=true
    envVars:
      - key: BASE_URL
        sync: false
      - key: PYTHON_VERSION
        value: 3.11.0
